spring:
  datasource:
#    url: jdbc:h2:mem:unidatabase
    url: jdbc:h2:file:C:\Users\Elena\Documents\PraktikumOOPBD\db
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    mvc:
      view:
        suffix: .html
  h2:
    console.enabled: true
springdoc:
  swagger-ui:
    operationsSorter: method