spring:
  datasource:
    url: jdbc:h2:mem:unidatabase
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    mvc:
      view:
        suffix: .html
  h2:
    console.enabled: true